### ISSUE TITLE
Asteroid spawn outside bounds error

### ISSUE THREAD

**Issue by Tislom58** [George-Doge/Space_game#19]
Destroying some asteroids will cause more to spawn, but when moving outside the spawn area with the space station, asteroid spawning produces an error.

```Traceback (most recent call last):
  File "../Space_game/main.py", line 613, in <module>
    asteroidSpawnerInstance.update()
  File "../Space_game/main.py", line 455, in update
    self.spawn_location()
  File "../Space_game/main.py", line 429, in spawn_location
    self.randomx = random.randint(self.spawnX, self.spawn_width)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../python3.12/random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "../python3.12/random.py", line 301, in randrange
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

Process finished with exit code 1```

**Comment by George-Doge** [comment]
Thank you, the bug was fixed in the latest commit.
